name: Build and Deploy

# 全ブランチで実行
on:
  push:
    branches: ["*"]

jobs:
  # 全ブランチでビルドを試す
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm ci
      - name: Build React App
        run: |
          npm run build
          ls -R

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check dist directory
        run: ls -R
      # - name: Upload to S3
      #   uses: jakejarvis/s3-sync-action@v0.5.0
      #   with:
      #     args: --exclude '.git/*' --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "ap-northeast-1"
      #     SOURCE_DIR: "dist"
